openapi: 3.0.0
info:
  title: Interview API
  description: API documentation for the Interview application
  version: 1.0.0
servers:
  - url: http://localhost:3000
    description: Local server
paths:
  /:
    get:
      summary: Get home page
      responses:
        '200':
          description: OK
  /signin:
    post:
      summary: Sign in a user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
      responses:
        '200':
          description: OK
        '400':
          description: Bad request
        '404':
          description: User not found
        '401':
          description: Unauthorized
  /signup:
    post:
      summary: Sign up a new user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
                email:
                  type: string
      responses:
        '201':
          description: Created
        '400':
          description: Bad request
        '409':
          description: Conflict
        '500':
          description: Internal server error
  /confirm/{token}:
    get:
      summary: Confirm user's email
      parameters:
        - name: token
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
        '404':
          description: Not found
        '500':
          description: Internal server error
